database:
  csv_file: "/Users/raahimlone/rahhh/Data_Gathering/masked.csv"  # Primary CSV
  csv_file2: "/Users/raahimlone/rahhh/Data_Gathering/query_latency_test.csv"
  query_path: "/Users/raahimlone/imdb_pg_dataset-1/job"
  hint_path: "/Users/raahimlone/rahhh/data/raw_hints"

  # Secondary CSV

paths:
  processed_features: "/Users/raahimlone/New_Data"
  queries_features: "/Users/raahimlone/New_Data/X.parquet"  # Path to query features
  hints_features: "/Users/raahimlone/New_Data/Y.parquet"        # Path to hint features
  query_path: "/Users/raahimlone/imdb_pg_dataset-1/job"
  hint_path: "/Users/raahimlone/rahhh/data/raw_hints"
  model_checkpoints: "/Users/raahimlone/New_Data/"


logging:
  log_file: "/Users/raahimlone/rahhh/Data_Gathering/log_file.log"
  log_level: "INFO"


features:
  F_q: 60  # Number of query features (adjust based on your data)
  F_h: 6  # Number of hint features (adjust based on your data)


training:
  latent_dim: 5          
  lambda_reg: 1        # Regularization parameter
  max_iters: 100          # Maximum number of iterations for ALS
  top_m: 5               # Number of top hint-query pairs to select in LimeQO_IC
  learning_rate: 0.0001     # Learning rate for gradient descent




logging:
  log_level: "DEBUG"
  log_file: "logs/system.log"
  max_bytes: 10485760
  backup_count: 5

